### ISSUE TITLE
Using predefined _id

### ISSUE THREAD

**Issue by aramk** [Meteor-Community-Packages/meteor-collection2#148]
I'm creating an unmanaged/unnamed collection on the client and then inserting a doc with a predefined ID:

```
var customers = Collections.createTemporary();
customers.insert({_id: 'foo', name: 'bar'});
```

This works fine. If I also attach a schema to this collection, then I'm no longer able to use a predefined ID. This is because simple-schema removes _id when cleaning since `allowsKey()` returns false. I added a condition to allow `_id` here but then noticed the field is actually removed temporarily in collection2 before validation. See [here](https://github.com/aldeed/meteor-collection2/blob/master/collection2.js#L225) and [here](https://github.com/aldeed/meteor-collection2/blob/master/collection2.js#L442).

I think the fix would be to allow this on the client as well, but I'm not sure why you've limited it to the server. Why would the id be needed on client collections during validation?

**Comment by jedwards1211** [comment]
@aramk MongoDB supports a lot of surprising things as IDs including objects.  I'm pretty sure it supports numbers too.  The limitation is due to Meteor's Minimongo: since JS maps with object keys compare instance equality and not deep value equality, there's not really a nice way Meteor would be able to make it work on the client side with Minimongo.

**Comment by aramk** [comment]
@jedwards1211 yeah it seems like strings are the way to go

**Comment by jedwards1211** [comment]
Well for one of my use cases objects would have been better if I didn't have to use Meteor actually.
